<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run() {
//        factory(App\Product::class, 50)->create();
        DB::table('products')->truncate();
        DB::table('products')->insert([
            [
                'user_id' => 2,
                'category_id' => 4,
                'brand_id' => 1,
                'name' => 'MatteTrance™ Lipstick',
                'price' => 38,
                'image' => '4-3-1.png',
                'image_list' => '4-3-5.png,4-3-4.png,4-3-3.png,4-3-2.png',
                'description' => 'A richly pigmented lipstick that adorns lips in a lightweight veil of opaque color for a modern, matte finish. ',
                'quantity' => 20,
            ],
            [
                'user_id' => 3,
                'category_id' => 4,
                'brand_id' => 2,
                'name' => 'Color Splash Seaglass Lipstick - Rainforest of the Sea™ Collection',
                'price' => 21,
                'image' => '4-2-1.png',
                'image_list' => '4-2-2.png,4-2-3.png,4-2-4.png',
                'description' => 'An ultra-creamy, pigmented lipstick with a sparkling, glittery finish to take your lips from basic to magical in seconds.',
                'quantity' => 20,
            ],
            [
                'user_id' => 3,
                'category_id' => 4,
                'brand_id' => 3,
                'name' => '3CE Velvet Lip Tint',
                'price' => 14,
                'image' => '4-1-1.png',
                'image_list' => '4-1-2.png,4-1-3.png,4-1-4.png',
                'description' => 'A lip tint with a sherbet-like texture that melts into the lips and leaves a natural tinge with a matte finish.',
                'quantity' => 20,
            ],
            [
                'user_id' => 2,
                'category_id' => 5,
                'brand_id' => 4,
                'name' => 'Glow Perfection Foundation',
                'price' => 71,
                'image' => '5-2-1.png',
                'image_list' => '5-2-2.png,5-2-3.png',
                'description' => 'This Sephora Collection foundation unifies skin tone, boosts radiance and smoothens your skin texture.',
                'quantity' => 20,
            ],
            [
                'user_id' => 2,
                'category_id' => 5,
                'brand_id' => 5,
                'name' => 'MAC Studio Fix Powder Plus Foundation',
                'price' => 94,
                'image' => '5-1-1.png',
                'image_list' => '5-1-2.png,5-1-3.png,5-1-4.png',
                'description' => 'A one-step powder and foundation that gives skin a smooth, flawless, all-matte finish with medium-to-full coverage and a velvety texture that allows skin to breathe',
                'quantity' => 20,
            ],
            [
                'user_id' => 3,
                'category_id' => 6,
                'brand_id' => 1,
                'name' => 'Better Than Mascara',
                'price' => 84,
                'image' => '6-3-2,png',
                'image_list' => '6-3-1.png,6-3-3.png,mascara1.jpg',
                'description' => 'A bold black mascara for intensely black, multidimensional lashes.',
                'quantity' => 20,
            ],
            [
                'user_id' => 3,
                'category_id' => 6,
                'brand_id' => 2,
                'name' => 'Grandiose Waterproof Mascara',
                'price' => 139,
                'image' => '6-2-1.png',
                'image_list' => 'mascara3.jpg,mascara2.jpg',
                'description' => 'A 24-hour waterproof mascara that\'s bent to work with the shape of your face for access to all lashes.',
                'quantity' => 20,
            ],
            [
                'user_id' => 2,
                'category_id' => 6,
                'brand_id' => 3,
                'name' => 'Perversion Mascara',
                'price' => 49,
                'image' => 'mascara1.jpg',
                'image_list' => '6-1-1.png,6-1-2.png',
                'description' => 'A creamy, lengthening mascara for instantly noticeable lashes.',
                'quantity' => 20,
            ],
            [
                'user_id' => 2,
                'category_id' => 7,
                'brand_id' => 4,
                'name' => 'Rinse-Off Foaming Cleanser',
                'price' => 52,
                'image' => '7-1-1.png',
                'image_list' => 'clean1.jpeg,7-1-1.png,clean3.jpeg',
                'description' => 'Foamy cream-mousse cleanser removes long-wearing makeup and sunscreens quickly, gently, efficiently. Comforts with botanicals.',
                'quantity' => 20,
            ],
            [
                'user_id' => 3,
                'category_id' => 7,
                'brand_id' => 5,
                'name' => 'Enzyme Cleansing Gel',
                'price' => 68,
                'image' => '7-2-1.png',
                'image_list' => '7-2-2.png,clean2.jpeg,7-2-1.png',
                'description' => 'A gel consisting of a non-foaming formula that thoroughly removes impurities without drying the skin.',
                'quantity' => 20,
            ],
            [
                'user_id' => 3,
                'category_id' => 8,
                'brand_id' => 1,
                'name' => 'Global Suncare Perfect UV Protector',
                'price' => 70,
                'image' => '8-3-1.png',
                'image_list' => '8-3-2.png,8-3-3.png',
                'description' => 'A lightweight protective sunscreen for the face and body that becomes more effective when it comes into contact with water, delivering the best coverage under the sun for healthy-looking, beautiful skin.',
                'quantity' => 20,
            ],
            [
                'user_id' => 2,
                'category_id' => 8,
                'brand_id' => 2,
                'name' => 'Everyday Sun Cream',
                'price' => 65,
                'image' => '8-2-1.png',
                'image_list' => 'kcn2.jpg,kcn1.png,8-1-2.png ',
                'description' => 'A moisturising sunscreen for well-protected, healthy skin.',
                'quantity' => 20,
            ],
            [
                'user_id' => 2,
                'category_id' => 8,
                'brand_id' => 3,
                'name' => 'Dr. Weil For Origins™ Mega-Defense Advanced Daily UV Defender SPF45/ PA++++',
                'price' => 86,
                'image' => 'kcn1.png',
                'image_list' => '8-1-1.png,8-1-2.png',
                'description' => 'A powerful UV defender to protect skin from UV rays, pollution, and environmental stress.',
                'quantity' => 20,
            ],
            [
                'user_id' => 3,
                'category_id' => 9,
                'brand_id' => 4,
                'name' => 'Glow Tonic',
                'price' => 68,
                'image' => '9-2-1.png',
                'image_list' => '9-2-2.png,toner1.jpg,toner2.jpg',
                'description' => 'A gently exfoliating toner for more even, brighter and clearer skin.',
                'quantity' => 20,
            ],
            [
                'user_id' => 3,
                'category_id' => 9,
                'brand_id' => 5,
                'name' => 'SEPHORA COLLECTION Instant Refreshing Toner',
                'price' => 30,
                'image' => '9-1-1.png',
                'image_list' => '9-1-2.png,toner3.jpeg',
                'description' => 'Its mission: to perfect cleansing and tone the skin. Its secret weapon for making this mission a reality: refreshing and toning ginseng extract',
                'quantity' => 20,
            ],
            [
                'user_id' => 2,
                'category_id' => 10,
                'brand_id' => 1,
                'name' => 'Splendidly Silky Moisturising Conditioner',
                'price' => 90,
                'image' => 'hair3.jpg',
                'image_list' => '10-2-1.png,10-3-2.png,hair2.jpg',
                'description' => 'Percy & Reed Splendidly Silky Moisturising Conditioner is packed with moisturising marvels.',
                'quantity' => 20,
            ],
            [
                'user_id' => 2,
                'category_id' => 10,
                'brand_id' => 2,
                'name' => 'Botanical Shampoo (Moist A)',
                'price' => 73,
                'image' => '10-2-1.png',
                'image_list' => '10-3-2.png,hair2.jpg',
                'description' => 'A moisturising shampoo infused with a high concentration of natural botanicals, including fragrant jasmine and sweet apricot.',
                'quantity' => 20,
            ],
            [
                'user_id' => 3,
                'category_id' => 10,
                'brand_id' => 3,
                'name' => 'Wonder to Go! Perfectly Perfecting Wonder Shampoo and Conditioner Duo',
                'price' => 75,
                'image' => 'hair1.jpeg',
                'image_list' => '10-3-2.png,hair3.jpg',
                'description' => 'A shampoo and conditioner set to take with you on the go and still have that wondrous shine.',
                'quantity' => 20,
            ],
            [
                'user_id' => 3,
                'category_id' => 11,
                'brand_id' => 4,
                'name' => 'Nourishing Shower Balm Body Wash',
                'price' => 21,
                'image' => '11-1-2.png',
                'image_list' => '11-1-1.png,11-2-3.png,11-2-4.png',
                'description' => 'A nourishing shower balm in six addictive scents that allows you to take time for yourself.',
                'quantity' => 20,
            ],
            [
                'user_id' => 2,
                'category_id' => 11,
                'brand_id' => 5,
                'name' => 'Fresh Moisturizing Body Milk',
                'price' => 29,
                'image' => '11-2-2.png',
                'image_list' => '11-2-1.png,11-2.png,11-1-3.png',
                'description' => 'A moisturising body milk with a refreshing texture for beautiful skin that stays hydrated all day long.',
                'quantity' => 20,
            ],
        ]);
    }
}
